# Generated by Django 3.0.2 on 2020-01-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('income', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_1960', models.CharField(max_length=500)),
                ('year_1961', models.CharField(max_length=500)),
                ('year_1962', models.CharField(max_length=500)),
                ('year_1963', models.CharField(max_length=500)),
                ('year_1964', models.CharField(max_length=500)),
                ('year_1965', models.CharField(max_length=500)),
                ('year_1966', models.CharField(max_length=500)),
                ('year_1967', models.CharField(max_length=500)),
                ('year_1968', models.CharField(max_length=500)),
                ('year_1969', models.CharField(max_length=500)),
                ('year_1970', models.CharField(max_length=500)),
                ('year_1971', models.CharField(max_length=500)),
                ('year_1972', models.CharField(max_length=500)),
                ('year_1973', models.CharField(max_length=500)),
                ('year_1974', models.CharField(max_length=500)),
                ('year_1975', models.CharField(max_length=500)),
                ('year_1976', models.CharField(max_length=500)),
                ('year_1977', models.CharField(max_length=500)),
                ('year_1978', models.CharField(max_length=500)),
                ('year_1979', models.CharField(max_length=500)),
                ('year_1980', models.CharField(max_length=500)),
                ('year_1981', models.CharField(max_length=500)),
                ('year_1982', models.CharField(max_length=500)),
                ('year_1983', models.CharField(max_length=500)),
                ('year_1984', models.CharField(max_length=500)),
                ('year_1985', models.CharField(max_length=500)),
                ('year_1986', models.CharField(max_length=500)),
                ('year_1987', models.CharField(max_length=500)),
                ('year_1988', models.CharField(max_length=500)),
                ('year_1989', models.CharField(max_length=500)),
                ('year_1990', models.CharField(max_length=500)),
                ('year_1991', models.CharField(max_length=500)),
                ('year_1992', models.CharField(max_length=500)),
                ('year_1993', models.CharField(max_length=500)),
                ('year_1994', models.CharField(max_length=500)),
                ('year_1995', models.CharField(max_length=500)),
                ('year_1996', models.CharField(max_length=500)),
                ('year_1997', models.CharField(max_length=500)),
                ('year_1998', models.CharField(max_length=500)),
                ('year_1999', models.CharField(max_length=500)),
                ('year_2000', models.CharField(max_length=500)),
                ('year_2001', models.CharField(max_length=500)),
                ('year_2002', models.CharField(max_length=500)),
                ('year_2003', models.CharField(max_length=500)),
                ('year_2004', models.CharField(max_length=500)),
                ('year_2005', models.CharField(max_length=500)),
                ('year_2006', models.CharField(max_length=500)),
                ('year_2007', models.CharField(max_length=500)),
                ('year_2008', models.CharField(max_length=500)),
                ('year_2009', models.CharField(max_length=500)),
                ('year_2010', models.CharField(max_length=500)),
                ('year_2011', models.CharField(max_length=500)),
                ('year_2012', models.CharField(max_length=500)),
                ('year_2013', models.CharField(max_length=500)),
                ('year_2014', models.CharField(max_length=500)),
                ('year_2015', models.CharField(max_length=500)),
                ('year_2016', models.CharField(max_length=500)),
                ('year_2017', models.CharField(max_length=500)),
                ('year_2018', models.CharField(max_length=500)),
                ('year_2019', models.CharField(max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Country', verbose_name='stat_country')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Indicator', verbose_name='stat_indicator')),
            ],
        ),
    ]
